In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv('DataSet/customer.csv')

In [18]:
df.sample(5)

age  gender   review education purchased
42   30  Female     Good        PG       Yes
33   89  Female     Good        PG       Yes
31   22  Female     Poor    School       Yes
45   61    Male     Poor        PG       Yes
5    31  Female  Average    School       Yes

In [21]:
df=df.iloc[:,2:]

In [22]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [31]:
X = df.iloc[:, 0:2]    # Selects first two columns
y = df.iloc[:, -1]     # Selects the last column


In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2)

In [34]:
X_train

review education
35     Poor    School
21  Average        PG
36     Good        UG
48     Good        UG
47     Good        PG
14     Poor        PG
38     Good    School
42     Good        PG
40     Good    School
8   Average        UG
39     Poor        PG
49     Good        UG
5   Average    School
33     Good        PG
6      Good    School
30  Average        UG
44  Average        UG
23     Good    School
12     Poor    School
15     Poor        UG
22     Poor        PG
0   Average    School
9      Good        UG
41     Good        PG
18     Good    School
37  Average        PG
31     Poor    School
2      Good        PG
26     Poor        PG
13  Average    School
45     Poor        PG
4   Average        UG
17     Poor        UG
16     Poor        UG
3      Good        PG
46     Poor        PG
28     Poor    School
32  Average        UG
20  Average    School
19     Poor        PG

In [35]:
y_train

35    Yes
21     No
36    Yes
48    Yes
47    Yes
14    Yes
38     No
42    Yes
40     No
8      No
39     No
49     No
5     Yes
33    Yes
6      No
30     No
44     No
23     No
12     No
15     No
22    Yes
0      No
9     Yes
41    Yes
18     No
37    Yes
31    Yes
2      No
26     No
13     No
45    Yes
4      No
17    Yes
16    Yes
3      No
46     No
28     No
32    Yes
20    Yes
19    Yes
Name: purchased, dtype: object

In [36]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [37]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [38]:
X_train = oe.transform(X_train)

In [39]:
X_train

array([[0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.]])

In [40]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [41]:
X_train

array([[0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 2.]])

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
le = LabelEncoder()

In [44]:
le.fit(y_train)

LabelEncoder()

In [45]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [46]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [47]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1])